### Model Class name
modelClass: Waka\MailMjml\Models\MailMjml

###TOOLBAR
tool_bar:
    create: 
        label: waka.mailmjml::lang.mailmjml.controller.create
        url: waka/mailmjml/wakamails/create
        show: true
    reorder: 
        show: false
        url: waka/mailmjml/wakamails/reorder
    delete: 
        show: true

###BREADCRUMP
breadcrump:
    inSettings: true
    indexUrl: waka/mailmjml/mailmjmls/
    indexlabel: waka.mailmjml::lang.mailmjml.controller.index_label
    title: waka.wutils::lang.controllers.title


          
    
        



