fields: 
    tos: 
        label: Emails
        type: taglist
        mode: array
        options: getEmails

    subject:
        label: Sujet

    embedImage:
        label: Embarquer les images
        type: checkbox 
        comment: Disponible uniquement pour outlook
