fields: 
    tos: 
        label: Emails
        type: taglist
        mode: array
        options: getEmails

    subject:
        label: Sujet

    embedImage:
        label: Embarquer les images
        type: dropdown
        options: 
            inherit: Hériter
            true: Oui
            false: Non
        comment: Pouur email API ou outlook ( uniquement en mode brouillon)
