# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.mailmjml::lang.controllers.layouts.label

# Model Form Field configuration
form: $/waka/mailmjml/models/layout/fields.yaml

# Model Class name
modelClass: Waka\MailMjml\Models\Layout

# Default redirect location
defaultRedirect: waka/mailmjml/layouts

# Create page
create:
    title: backend::lang.form.create_title
    redirect: waka/mailmjml/layouts/update/:id
    redirectClose: waka/mailmjml/layouts

# Update page
update:
    title: backend::lang.form.update_title
    redirect: waka/mailmjml/layouts/update/:id
    redirectClose: waka/mailmjml/layouts

# Preview page
preview:
    title: backend::lang.form.preview_title
