# ===================================
#  WakaController | Workflow | Productor |  Behavior Config
# ===================================


modelClass: Waka\MailMjml\Models\Layout
backendUrl: waka/mailmjml/layouts

workflow: false 

controllerConfig:
    breadcrump:
        inSettings: true 
        title: waka.mailmjml::lang.models.layout.label
        rows:    
            preIndex: 
                label: waka.mailmjml::lang.controllers.mailmjmls.label
                url:  waka/mailmjml/mailmjmls 
            index: 
                url: waka/mailmjml/layouts 
                label: waka.mailmjml::lang.controllers.layouts.label
    index:
        base:
            create: 
                show: true
                permissions: [waka.mailmjml.*]
            reorder: 
                show: false  
                permissions: []
            delete: 
                show: true
                permissions: [waka.mailmjml.*]
        partials:
            index_btn:
                url: $/waka/mailmjml/controllers/layouts/_index_btn.php
    partials:   
            return: 
                url: $/waka/mailmjml/controllers/layouts/_return_btn.htm


